import {
  Calendar,
  Cloud,
  Cpu,
  CreditCard,
  Github,
  Globe,
  Mail,
  Slack,
} from "lucide-react";

import type { StudioPluginConfig } from "@/types/studio";

export const studioPlugins: StudioPluginConfig[] = [
  {
    id: "google-search",
    name: "Google Search",
    provider: "official",
    descKey: "googleSearch",
    icon: Globe,
    color: "text-blue-600",
    bg: "bg-blue-50",
    installed: true,
  },
  {
    id: "github-sync",
    name: "GitHub Sync",
    provider: "official",
    descKey: "githubSync",
    icon: Github,
    color: "text-black",
    bg: "bg-gray-100",
    installed: true,
  },
  {
    id: "slack-bot",
    name: "Slack Bot",
    provider: "official",
    descKey: "slackBot",
    icon: Slack,
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    installed: false,
  },
  {
    id: "stripe-payments",
    name: "Stripe Payments",
    provider: "nexus",
    descKey: "stripePayments",
    icon: CreditCard,
    color: "text-emerald-600",
    bg: "bg-emerald-50",
    installed: false,
  },
  {
    id: "postmark-email",
    name: "Postmark Email",
    provider: "nexus",
    descKey: "postmarkEmail",
    icon: Mail,
    color: "text-amber-600",
    bg: "bg-amber-50",
    installed: false,
  },
  {
    id: "cron-scheduler",
    name: "Cron Scheduler",
    provider: "nexus",
    descKey: "cronScheduler",
    icon: Calendar,
    color: "text-rose-600",
    bg: "bg-rose-50",
    installed: true,
  },
  {
    id: "vercel-deploy",
    name: "Vercel Deploy",
    provider: "community",
    descKey: "vercelDeploy",
    icon: Cloud,
    color: "text-black",
    bg: "bg-stone-100",
    installed: false,
  },
  {
    id: "wolfram-alpha",
    name: "Wolfram Alpha",
    provider: "community",
    descKey: "wolframAlpha",
    icon: Cpu,
    color: "text-red-600",
    bg: "bg-red-50",
    installed: false,
  },
];
